# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9   # Needed for C++11
    - g++-4.9   # Needed for C++11
    - gdb
    - ccache
    - valgrind
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libjemalloc-dev
    - gtk-doc-tools
    - autoconf-archive
    - libgirepository1.0-dev

services:
  - docker

cache:
  ccache: true

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
  include:
  # C++ & Python w/ clang 4.0
  - compiler: gcc
    language: cpp
    os: linux
    group: deprecated
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - export ARROW_TRAVIS_USE_TOOLCHAIN=1
    - export ARROW_TRAVIS_VALGRIND=1
    - export ARROW_TRAVIS_PLASMA=1
    - export ARROW_TRAVIS_ORC=1
    - export ARROW_TRAVIS_CLANG_FORMAT=1
    - export ARROW_BUILD_WARNING_LEVEL=CHECKIN
    - export CC="clang-4.0"
    - export CXX="clang++-4.0"
    - $TRAVIS_BUILD_DIR/ci/travis_install_clang_tools.sh
    - $TRAVIS_BUILD_DIR/ci/travis_lint.sh
    - if [ $ARROW_CI_CPP_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh; fi
    script:
    - if [ $ARROW_CI_CPP_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_cpp.sh; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_build_parquet_cpp.sh; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_python.sh 2.7; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_python.sh 3.6; fi
  # [OS X] C++ & Python w/ XCode 6.4
  - compiler: clang
    language: cpp
    osx_image: xcode6.4
    os: osx
    cache:
    addons:
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - export ARROW_TRAVIS_USE_TOOLCHAIN=1
    - export ARROW_TRAVIS_PLASMA=1
    - export ARROW_TRAVIS_ORC=1
    - export ARROW_BUILD_WARNING_LEVEL=CHECKIN
    - if [ $ARROW_CI_CPP_AFFECTED == "1" ]; then travis_wait 50 $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh; fi
    script:
    - if [ $ARROW_CI_CPP_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_cpp.sh; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_build_parquet_cpp.sh; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_python.sh 2.7; fi
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_python.sh 3.6; fi
  # [manylinux1] Python
  - language: cpp
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then docker pull quay.io/xhochy/arrow_manylinux1_x86_64_base:latest; fi
    script:
    - if [ $ARROW_CI_PYTHON_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_manylinux.sh; fi
  # Java w/ OpenJDK 7
  - language: java
    os: linux
    jdk: openjdk7
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    script:
    - if [ $ARROW_CI_JAVA_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_java.sh; fi
    - if [ $ARROW_CI_JAVA_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_javadoc.sh; fi
  # Java w/ Oracle JDK 9
  - language: java
    os: linux
    jdk: oraclejdk9
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    script:
    - if [ $ARROW_CI_JAVA_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_java.sh; fi
    addons:
      apt:
        packages:
          - oracle-java9-installer
  # Integration w/ OpenJDK 8
  - language: java
    os: linux
    env: ARROW_TEST_GROUP=integration
    jdk: openjdk8
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - source $TRAVIS_BUILD_DIR/ci/travis_install_clang_tools.sh
    - export CC="clang-4.0"
    - export CXX="clang++-4.0"
    - nvm install node
    - if [ $ARROW_CI_INTEGRATION_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_js.sh; fi
    - if [ $ARROW_CI_INTEGRATION_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh; fi
    script:
    - if [ $ARROW_CI_INTEGRATION_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_integration.sh; fi
  # NodeJS
  - language: node_js
    os: linux
    node_js: node
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - if [ $ARROW_CI_JS_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_js.sh; fi
    script:
    - if [ $ARROW_CI_JS_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_js.sh; fi
  # C++ & glib w/ gcc 4.9 & autotools
  - compiler: gcc
    language: cpp
    os: linux
    env: BUILD_SYSTEM=autotools BUILD_TORCH_EXAMPLE=no
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh --only-library; fi
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_c_glib.sh; fi
    script:
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_c_glib.sh; fi
  # C++ & glib w/ gcc 4.9 & meson
  - compiler: gcc
    language: cpp
    os: linux
    env: BUILD_SYSTEM=meson BUILD_TORCH_EXAMPLE=no
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh --only-library; fi
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_c_glib.sh; fi
    script:
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_c_glib.sh; fi
  # [OS X] C++ & glib w/ XCode 8.3 & autotools
  - compiler: clang
    osx_image: xcode8.3
    os: osx
    cache:
    addons:
    rvm: 2.2
    env: BUILD_SYSTEM=autotools
    before_script:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis_detect_changes.py`
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then brew update && brew bundle --file=$TRAVIS_BUILD_DIR/c_glib/Brewfile; fi
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh --only-library; fi
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_before_script_c_glib.sh; fi
    script:
    - if [ $ARROW_CI_C_GLIB_AFFECTED == "1" ]; then $TRAVIS_BUILD_DIR/ci/travis_script_c_glib.sh; fi

before_install:
- ulimit -c unlimited -S

after_failure:
- COREFILE=$(find . -maxdepth 2 -name "core*" | head -n 1)
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

env:
  global:
  - secure: "GcrPtsKUCgNY7HKYjWlHQo8SiFrShDvdZSU8t1m1FJrE+UfK0Dgh9zXmAausM8GmhqSwkF0q4UbLQf2uCnSITWKeEPAL8Mo9eu4ib+ikJx/b3Sk81frgW5ADoHfW1Eyqd8xJNIMwMegJOtRLSDqiXh1CvMlKnY8PyTOGM2DgN9ona/v6p9OFH9Qs0JhBRVXAn0S4ztjumck8E56+01hqRfxbZ88pTfpKghBxYp9PJaMjtGdomjVWlqPaWaWJj+KptT8inV9NK+TVYKx0dXWD+S1Vgr1PytQnLdILOYV23gsOBYqn33ByF/yADl4m3hUjU/qeT0Fi7aWxmVpj+oTJISOSH5N8nIsuNH8mQk2ZzzXHfV7btFvP+cOPRczadoKkT6D6cHA8nQ7b0dphC6bl6SAeSfc/cbhRT+fYnIjg8jFXC8jlyWBr7LR6GXVpc0bND7i300ITo0FuRJhy2OxqPtGo3dKLE7eAcv78tuO0OYJ/kol1PEqFdFkbYbNVbg/cFpbGqiCXDsOtPDbAGBv69YnXdVowSxxs8cRGjSkDydv6ZSytb/Zd4lH/KAomcFNk8adx12O1Lk4sbmVav1cGig5P6OcQKS0jC5IiRb4THcQzVzAkXXbaafKm5sru/NoYxhzmkyhkOc11nTYHKVng+XKWzLCNn7pTTSLitp5+xa4="
