# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Python Cron

on:
  schedule:
    - cron: |
        0 */12 * * *

jobs:

  debian:
    name: AMD64 Debian ${{ matrix.debian }} Python 3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian: [10]
    env:
      DEBIAN: ${{ matrix.debian }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures debian-cpp
          docker-compose pull --ignore-pull-failures debian-python
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build debian-cpp
          docker-compose build debian-python
      - name: Docker Run
        shell: bash
        run: docker-compose run debian-python
      - name: Docker Push
        if: success() && github.repository == 'apache/arrow'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push debian-python

  fedora:
    name: AMD64 Fedora ${{ matrix.fedora }} Python 3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora: [29]
    env:
      FEDORA: ${{ matrix.fedora }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures fedora-cpp
          docker-compose pull --ignore-pull-failures fedora-python
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build fedora-cpp
          docker-compose build fedora-python
      - name: Docker Run
        shell: bash
        run: docker-compose run fedora-python
      - name: Docker Push
        if: success() && github.repository == 'apache/arrow'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push fedora-python

  downstream:
    name: AMD64 Conda Python 3.7 ${{ matrix.title }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - dask
          - hdfs
          - turbodbc
          - pandas-master
          - pandas-0.24
        include:
          - name: dask
            library: dask
            title: Dask
          - name: turbodbc
            library: turbodbc
            title: Turbodbc
          - name: pandas-0.24
            library: pandas
            title: Pandas 0.24
            pandas: 0.24
          - name: pandas-master
            library: pandas
            title: Pandas master
            pandas: master
          - name: hdfs
            library: hdfs
            title: HDFS
    env:
      PYTHON: 3.7
      DASK: latest
      TURBODBC: latest
      PANDAS: ${{ matrix.pandas || 'latest' }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures conda-cpp
          docker-compose pull --ignore-pull-failures conda-python
          docker-compose pull --ignore-pull-failures conda-python-${{ matrix.library }}
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build conda-cpp
          docker-compose build conda-python
          docker-compose build conda-python-${{ matrix.library }}
      - name: Docker Run
        shell: bash
        run: |
          docker-compose run conda-python-${{ matrix.library }}
      - name: Docker Push
        if: success() && github.repository == 'apache/arrow'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push conda-python-${{ matrix.library }}
